logger.py-32-yanfeng-WARNING-123-2021-08-31 11:04:30,181
basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-08-31 23:43:55,192
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: 'using' must be a string
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-08-31 23:44:50,121
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="kd"]"}
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-08-31 23:46:25,788
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 00:04:59,393
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 00:13:56,681
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 00:29:02,077
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 00:34:07,255
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 16:35:29,540
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 16:51:52,776
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 16:55:26,371
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 16:56:11,864
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 16:58:42,112
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:00:17,792
basepage.py-143-yanfeng-INFO-“≥√ÊÕº∆¨±£¥Ê‘⁄£∫F:\python25-web-base\PO\Outouts/screenshots\yanf_2021-09-01 17:00:17-2021-09-01 17:00:18,264
basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 17:00:18,265
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:01:42,333
basepage.py-143-yanfeng-INFO-“≥√ÊÕº∆¨±£¥Ê‘⁄£∫F:\python25-web-base\PO\Outouts/screenshots\yanf_2021-09-0117:01:42-2021-09-01 17:01:42,810
basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 17:01:42,810
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:03:51,302
basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:04:36,401
basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:08:28,617
basepage.py-144-yanfeng-INFO-“≥√ÊÕº∆¨±£¥Ê‘⁄£∫F:\python25-web-base\PO\Outouts/screenshots\yanf_17:08:28.png-2021-09-01 17:08:29,071
basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 17:08:29,071
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

basepage.py-36-yanfeng-INFO-‘⁄yanf≤È’“‘™Àÿ('ID', 'kd1')-2021-09-01 17:12:45,528
basepage.py-143-yanfeng-INFO-“≥√ÊÕº∆¨±£¥Ê‘⁄£∫F:\python25-web-base\PO\Outouts/screenshots/yanf_2021-09-01 17_12_45.png-2021-09-01 17:12:46,084
basepage.py-41-yanfeng-ERROR-≤È’“‘™Àÿ ß∞‹-2021-09-01 17:12:46,084
Traceback (most recent call last):
  File "F:/python25-web-base/PO/Common/basepage.py", line 38, in get_emement
    ele = self.driver.find_element(*loc)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: invalid locator
  (Session info: chrome=92.0.4515.159)

test_login.py-11-yanfeng-INFO-login”√¿˝µƒ«∞÷√-2021-09-18 13:55:25,217
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î13313532504-2021-09-18 13:55:25,222
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-18 13:55:25,223
basepage.py-171-yanfeng-INFO-“≥√ÊÕº∆¨±£¥Ê‘⁄£∫F:\python25-web-base\PO\Outouts/screenshots/µ«¬º“≥√Ê_ ‰»Î”√ªß√˚_2021-09-18 13_55_45.png-2021-09-18 13:55:45,373
basepage.py-31-yanfeng-ERROR-µ»¥˝‘™Àÿø…º˚ ß∞‹£∫-2021-09-18 13:55:45,373
Traceback (most recent call last):
  File "F:\python25-web-base\PO\Common\basepage.py", line 28, in wait_ele_visible
    WebDriverWait(self.driver,timeout,poll_frequency=poll_fre).until(EC.visibility_of_element_located(loc))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

test_login.py-14-yanfeng-INFO-login”√¿˝µƒ∫Û÷√-2021-09-18 13:55:45,726
test_login.py-11-yanfeng-INFO-login”√¿˝µƒ«∞÷√-2021-09-18 13:55:53,611
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î-2021-09-18 13:55:53,613
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-18 13:55:53,614
test_login.py-14-yanfeng-INFO-login”√¿˝µƒ∫Û÷√-2021-09-18 13:56:20,432
test_login.py-11-yanfeng-INFO-login”√¿˝µƒ«∞÷√-2021-09-18 13:56:33,263
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î18713532504-2021-09-18 13:56:33,266
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-18 13:56:33,266
test_login.py-14-yanfeng-INFO-login”√¿˝µƒ∫Û÷√-2021-09-18 13:56:52,172
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î13313532504-2021-09-23 16:39:36,479
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-23 16:39:36,589
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î13313532504-2021-09-23 16:40:27,298
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-23 16:40:27,298
test_login.py-11-yanfeng-INFO-login”√¿˝µƒ«∞÷√-2021-09-23 16:40:49,551
basepage.py-80-yanfeng-INFO-‘⁄µ«¬º“≥√Ê_ ‰»Î”√ªß√˚∂‘‘™Àÿ('xpath', 'sadadad//') ‰»Î13313532504-2021-09-23 16:40:49,552
basepage.py-26-yanfeng-INFO-µ«¬º“≥√Ê_ ‰»Î”√ªß√˚µ»¥˝('xpath', 'sadadad//')‘™Àÿø…º˚°£-2021-09-23 16:40:49,552
